### ISSUE TITLE
AmneziaVPN crashed with SIGSEGV in QTimer::interval()

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [amnezia-vpn/amnezia-client#1062]
**Screenshots**
![images](https://github.com/user-attachments/assets/8365f602-3fbf-49fc-81a7-d47712e886c7)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version 4.7.0.0

**Server (please complete the following information):**
 - OS: Ubuntu 24.04

**Comment by Nethius** [comment]
please provide a full crushdump

**Comment by StackOverflowExcept1on** [comment]
@Nethius [_opt_AmneziaVPN_client_bin_AmneziaVPN.1000.crash](https://github.com/user-attachments/files/16976873/_opt_AmneziaVPN_client_bin_AmneziaVPN.1000.crash.log)

**Comment by varnie** [comment]
I confirm. I've got this crash a moment ago.
System:
 ```System:
  Host: heimdal Kernel: 6.1.106-1-MANJARO arch: x86_64 bits: 64
  Desktop: Xfce v: 4.18.1 Distro: Manjaro Linux
```
```
Sep 12 20:07:50 heimdal systemd-coredump[9751]: [🡕] Process 8819 (AmneziaVPN) of user 1000 dumped core.
                                                
                                                Stack trace of thread 8819:
                                                #0  0x00007f96fe7c8793 _ZNK6QTimer8intervalEv (libQt6Core.so.6 + 0x1c8793)
                                                #1  0x00007f9700962143 n/a (libQt6RemoteObjects.so.6 + 0xa5143)
                                                #2  0x000055f2e441f65d _ZN19IpcInterfaceReplica8flushDnsEv (AmneziaVPN + 0x17265d)
                                                #3  0x000055f2e44f7d4c _ZN13VpnConnection17disconnectFromVpnEv (AmneziaVPN + 0x24ad4c)
                                                #4  0x000055f2e44f46fc _ZN13VpnConnectionD1Ev (AmneziaVPN + 0x2476fc)
                                                #5  0x000055f2e44f4788 _ZN13VpnConnectionD0Ev (AmneziaVPN + 0x247788)
                                                #6  0x000055f2e44648b5 _ZN15QtSharedPointer13CustomDeleterI13VpnConnectionNS_13NormalDeleterEE7executeEv (AmneziaVPN + 0x1b78b5)
                                                #7  0x000055f2e44624e3 _ZN15QtSharedPointer33ExternalRefCountWithCustomDeleterI13VpnConnectionNS_13NormalDeleterEE7deleterEPNS_20ExternalRefCountD>
                                                #8  0x000055f2e43e29c3 _ZN15QtSharedPointer20ExternalRefCountData7destroyEv (AmneziaVPN + 0x1359c3)
                                                #9  0x000055f2e441db96 _ZN14QSharedPointerI13VpnConnectionE5derefEPN15QtSharedPointer20ExternalRefCountDataE (AmneziaVPN + 0x170b96)
                                                #10 0x000055f2e441d8c4 _ZN14QSharedPointerI13VpnConnectionE5derefEv (AmneziaVPN + 0x1708c4)
                                                #11 0x000055f2e441d5bc _ZN14QSharedPointerI13VpnConnectionED1Ev (AmneziaVPN + 0x1705bc)
                                                #12 0x000055f2e4454567 _ZN18AmneziaApplicationD1Ev (AmneziaVPN + 0x1a7567)
                                                #13 0x000055f2e44dc4be main (AmneziaVPN + 0x22f4be)
                                                #14 0x00007f96fe1f7e08 n/a (libc.so.6 + 0x25e08)
                                                #15 0x00007f96fe1f7ecc __libc_start_main (libc.so.6 + 0x25ecc)
                                                #16 0x000055f2e43ccdbe _start (AmneziaVPN + 0x11fdbe)
                                                
                                                Stack trace of thread 8820:
                                                #0  0x00007f96fe2dd63d __poll (libc.so.6 + 0x10b63d)
                                                #1  0x00007f96fe57092d n/a (libglib-2.0.so.0 + 0xbe92d)
                                                #2  0x00007f96fe50dfc5 g_main_context_iteration (libglib-2.0.so.0 + 0x5bfc5)
                                                #3  0x00007f96fea0472a _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt6Core.so.6 + 0x40472a)
                                                #4  0x00007f96fe768f03 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt6Core.so.6 + 0x168f03)
                                                #5  0x00007f96fe85d04c _ZN7QThread4execEv (libQt6Core.so.6 + 0x25d04c)
                                                #6  0x00007f96fedc3fda n/a (libQt6DBus.so.6 + 0x33fda)
                                                #7  0x00007f96fe8f271d n/a (libQt6Core.so.6 + 0x2f271d)
                                                #8  0x00007f96fe26639d n/a (libc.so.6 + 0x9439d)
                                                #9  0x00007f96fe2eb49c n/a (libc.so.6 + 0x11949c)
                                                
                                                Stack trace of thread 8822:
                                                #0  0x00007f96fe2e91fd syscall (libc.so.6 + 0x1171fd)
                                                #1  0x00007f96fe569a10 g_cond_wait (libglib-2.0.so.0 + 0xb7a10)
                                                #2  0x00007f96fe4d790c n/a (libglib-2.0.so.0 + 0x2590c)
                                                #3  0x00007f96fe5436b7 n/a (libglib-2.0.so.0 + 0x916b7)
                                                #4  0x00007f96fe53e266 n/a (libglib-2.0.so.0 + 0x8c266)
                                                #5  0x00007f96fe26639d n/a (libc.so.6 + 0x9439d)
                                                #6  0x00007f96fe2eb49c n/a (libc.so.6 + 0x11949c)
                                                
                                                Stack trace of thread 8825:
                                                #0  0x00007f96fe2e91fd syscall (libc.so.6 + 0x1171fd)
                                                #1  0x00007f96fe569a10 g_cond_wait (libglib-2.0.so.0 + 0xb7a10)
                                                #2  0x00007f96fe4d790c n/a (libglib-2.0.so.0 + 0x2590c)
                                                #3  0x00007f96fe4d797d g_async_queue_pop (libglib-2.0.so.0 + 0x2597d)
                                                #4  0x00007f96f88265fc n/a (libpangoft2-1.0.so.0 + 0xc5fc)
                                                #5  0x00007f96fe53e266 n/a (libglib-2.0.so.0 + 0x8c266)
                                                #6  0x00007f96fe26639d n/a (libc.so.6 + 0x9439d)
                                                #7  0x00007f96fe2eb49c n/a (libc.so.6 + 0x11949c)
                                                
                                                Stack trace of thread 8829:
                                                #0  0x00007f96fe262a19 n/a (libc.so.6 + 0x90a19)
                                                #1  0x00007f96fe265479 pthread_cond_wait (libc.so.6 + 0x93479)
                                                #2  0x00007f96cdca3eee n/a (iris_dri.so + 0xa3eee)
                                                #3  0x00007f96cdc80ecc n/a (iris_dri.so + 0x80ecc)
                                                #4  0x00007f96cdca3e1d n/a (iris_dri.so + 0xa3e1d)
                                                #5  0x00007f96fe26639d n/a (libc.so.6 + 0x9439d)
                                                #6  0x00007f96fe2eb49c n/a (libc.so.6 + 0x11949c)
                                                
                                                Stack trace of thread 8830:
                                                #0  0x00007f96fe262a19 n/a (libc.so.6 + 0x90a19)
                                                #1  0x00007f96fe265479 pthread_cond_wait (libc.so.6 + 0x93479)
                                                #2  0x00007f96cdca3eee n/a (iris_dri.so + 0xa3eee)
                                                #3  0x00007f96cdc80ecc n/a (iris_dri.so + 0x80ecc)
                                                #4  0x00007f96cdca3e1d n/a (iris_dri.so + 0xa3e1d)
                                                #5  0x00007f96fe26639d n/a (libc.so.6 + 0x9439d)
                                                #6  0x00007f96fe2eb49c n/a (libc.so.6 + 0x11949c)
                                                
                                                Stack trace of thread 8823:
                                                #0  0x00007f96fe2dd63d __poll (libc.so.6 + 0x10b63d)
                                                #1  0x00007f96fe57092d n/a (libglib-2.0.so.0 + 0xbe92d)
                                                #2  0x00007f96fe50dfc5 g_main_context_iteration (libglib-2.0.so.0 + 0x5bfc5)
                                                #3  0x00007f96fe50e01a n/a (libglib-2.0.so.0 + 0x5c01a)
                                                #4  0x00007f96fe53e266 n/a (libglib-2.0.so.0 + 0x8c266)
                                                #5  0x00007f96fe26639d n/a (libc.so.6 + 0x9439d)
                                                #6  0x00007f96fe2eb49c n/a (libc.so.6 + 0x11949c)
                                                
                                                Stack trace of thread 8821:
                                                #0  0x00007f96fe2dd63d __poll (libc.so.6 + 0x10b63d)
                                                #1  0x00007f96fd0d920b n/a (libxcb.so.1 + 0xd20b)
                                                #2  0x00007f96fd0daf3d xcb_wait_for_event (libxcb.so.1 + 0xef3d)
                                                #3  0x00007f96fa5a5270 n/a (libQt6XcbQpa.so.6 + 0x58270)
                                                #4  0x00007f96fe8f271d n/a (libQt6Core.so.6 + 0x2f271d)
                                                #5  0x00007f96fe26639d n/a (libc.so.6 + 0x9439d)
                                                #6  0x00007f96fe2eb49c n/a (libc.so.6 + 0x11949c)
                                                
                                                Stack trace of thread 8824:
                                                #0  0x00007f96fe2dd63d __poll (libc.so.6 + 0x10b63d)
                                                #1  0x00007f96fe57092d n/a (libglib-2.0.so.0 + 0xbe92d)
                                                #2  0x00007f96fe50f7b7 g_main_loop_run (libglib-2.0.so.0 + 0x5d7b7)
                                                #3  0x00007f96f89a7574 n/a (libgio-2.0.so.0 + 0x112574)
                                                #4  0x00007f96fe53e266 n/a (libglib-2.0.so.0 + 0x8c266)
                                                #5  0x00007f96fe26639d n/a (libc.so.6 + 0x9439d)
                                                #6  0x00007f96fe2eb49c n/a (libc.so.6 + 0x11949c)
                                                ELF object binary architecture: AMD x86-64
```

**Comment by Nethius** [comment]
try latest release https://github.com/amnezia-vpn/amnezia-client/releases/tag/4.8.1.0

**Comment by StackOverflowExcept1on** [comment]
@Nethius I updated client and had same problem after rebooting. Also, it might be worth noting that I have autostart, autoconnect, and minimized startup enabled.
```
 Thread 1 (Thread 0x7a4f03f28900 (LWP 2396)):
 #0  0x00007a4f059c8793 in QTimer::interval() const () at /opt/AmneziaVPN/client/lib/libQt6Core.so.6
 #1  0x00007a4f07b31143 in  () at /opt/AmneziaVPN/client/lib/libQt6RemoteObjects.so.6
 #2  0x00005f16a5fa765d in IpcInterfaceReplica::flushDns() ()
 #3  0x00005f16a607fd4c in VpnConnection::disconnectFromVpn() ()
 #4  0x00005f16a607c6fc in VpnConnection::~VpnConnection() ()
 #5  0x00005f16a607c788 in VpnConnection::~VpnConnection() ()
 #6  0x00005f16a5fec8b5 in QtSharedPointer::CustomDeleter<VpnConnection, QtSharedPointer::NormalDeleter>::execute() ()
 #7  0x00005f16a5fea4e3 in QtSharedPointer::ExternalRefCountWithCustomDeleter<VpnConnection, QtSharedPointer::NormalDeleter>::deleter(QtSharedPointer::ExternalRefCountData*) ()
 #8  0x00005f16a5f6a9c3 in QtSharedPointer::ExternalRefCountData::destroy() ()
 #9  0x00005f16a5fa5b96 in QSharedPointer<VpnConnection>::deref(QtSharedPointer::ExternalRefCountData*) ()
 #10 0x00005f16a5fa58c4 in QSharedPointer<VpnConnection>::deref() ()
 #11 0x00005f16a5fa55bc in QSharedPointer<VpnConnection>::~QSharedPointer() ()
 #12 0x00005f16a5fdc567 in AmneziaApplication::~AmneziaApplication() ()
 #13 0x00005f16a60644be in main ()
Title: AmneziaVPN crashed with SIGSEGV in QTimer::interval()
```

**Comment by w7rus** [comment]
Had same SIGSEGV on 4.7.0.0, updating to 4.8.1.0 helped a bit.

Found in amnezia service logs an error:

```
2024-09-21 22:10:13 debug Amnezia "DnsUtilsLinux" "Adding DNS resolver 1.1.1.1 via amn0"
2024-09-21 22:10:13 debug Amnezia "IPUtilsLinux" "Failed to set IPv6:  XXXXXXXX error: Permission denied"
2024-09-21 22:10:13 debug Amnezia "DaemonLocalServerConnection" "Failed to activate the interface"
2024-09-21 22:10:25 debug Amnezia "DaemonLocalServerConnection" "Connection released"
```

I had AmneziaDNS active, and disabled IPv6 completely to speed up Steam downloads. If you have disabled IPv6 in /etc/sysctl, enable it back again

```
# Commented out, since AmneziaDNS fails w/o IPv6 active
#net.ipv6.conf.all.disable_ipv6 = 1
#net.ipv6.conf.default.disable_ipv6 = 1
#net.ipv6.conf.lo.disable_ipv6 = 1
#net.ipv6.conf.tun0.disable_ipv6 = 1
```

@Nethius New release no more throws SIGSEGV due to that, but won't allow connecting with IPv6 disabled and AmneziaDNS active
