### ISSUE TITLE
Can't connect due to a crash

### ISSUE THREAD

**Issue by bileslav** [amnezia-vpn/amnezia-client#1257]
**Device:** Google Pixel 8
**OS:** GrapheneOS

### The problem

The _Connect_ button does not work in **4.8.2.3**. The OS reports a crash after pressing it. It works in **4.8.1.9**.

### The crash message

```
type: crash
osVersion: google/shiba/shiba:15/AP3A.241105.007/2024110700:user/release-keys
package: org.amnezia.vpn:1069, targetSdk 34
process: org.amnezia.vpn:amneziaAwgService
processUptime: 630 + 748 ms
installer: dev.imranr.obtainium.fdroid

java.lang.RuntimeException: Unable to start service org.amnezia.vpn.AwgService@777bea0 with Intent { cmp=org.amnezia.vpn/.AwgService (has extras) }: android.app.InvalidForegroundServiceTypeException: Starting FGS with type none callerApp=ProcessRecord{844b3bd 7799:org.amnezia.vpn:amneziaAwgService/u0a161} targetSDK=34 has been prohibited
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5199)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: android.app.InvalidForegroundServiceTypeException: Starting FGS with type none callerApp=ProcessRecord{844b3bd 7799:org.amnezia.vpn:amneziaAwgService/u0a161} targetSDK=34 has been prohibited
	at android.app.InvalidForegroundServiceTypeException$1.createFromParcel(InvalidForegroundServiceTypeException.java:53)
	at android.app.InvalidForegroundServiceTypeException$1.createFromParcel(InvalidForegroundServiceTypeException.java:49)
	at android.os.Parcel.readParcelableInternal(Parcel.java:5095)
	at android.os.Parcel.readParcelable(Parcel.java:5077)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3246)
	at android.os.Parcel.createException(Parcel.java:3235)
	at android.os.Parcel.readException(Parcel.java:3211)
	at android.os.Parcel.readException(Parcel.java:3153)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7231)
	at android.app.Service.startForeground(Service.java:879)
	at androidx.core.app.ServiceCompat$Api34Impl.startForeground(ServiceCompat.java:239)
	at androidx.core.app.ServiceCompat.startForeground(ServiceCompat.java:172)
	at org.amnezia.vpn.AmneziaVpnService.onStartCommand(AmneziaVpnService.kt:217)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5181)
	... 11 more
```

**Comment by ildvild** [comment]
the same problem on xiaomi 11T Pro

**Comment by Nethius** [comment]
Thank you for your report. Please note that GitHub is not a support channel. For assistance, please contact our support team via chat at https://t.me/amnezia_support_bot or via email at support@amnezia.org.

Our team will review the details and help resolve the issue.
