### ISSUE TITLE
VPN disconnected after 3 seconds

### ISSUE THREAD

**Issue by olegtrautvein** [amnezia-vpn/amnezia-client#1294]
**Describe the bug**
I click on circle to connect vpn, it beings 'connected' but after 2-3 seconds disconnects. One time I have ability to switch browser and check on ipchecker that I was there (other country) for seconds.

**Log files**
```
type: crash
osVersion: google/sunfish/sunfish:13/TQ3A.230805.001.S1/2024070401:user/release-keys
package: org.amnezia.vpn:1069
process: org.amnezia.vpn:amneziaAwgService
processUptime: 1762 + 303 ms
installer: com.android.packageinstaller

java.lang.SecurityException: org.amnezia.vpn was not granted either of these permissions:android.permission.CHANGE_NETWORK_STATE,android.permission.WRITE_SETTINGS.
 at android.os.Parcel.createExceptionOrNull(Parcel.java:3020)
 at android.os.Parcel.createException(Parcel.java:3004)
 at android.os.Parcel.readException(Parcel.java:2980)
 at android.os.Parcel.readException(Parcel.java:2922)
 at android.net.IConnectivityManager$Stub$Proxy.requestNetwork(IConnectivityManager.java:2338)
 at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4187)
 at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4206)
 at android.net.ConnectivityManager.requestNetwork(ConnectivityManager.java:4344)
 at android.net.ConnectivityManager.requestNetwork(ConnectivityManager.java:4322)
 at org.amnezia.vpn.util.net.NetworkState.bindNetworkListener(NetworkState.kt:82)
 at org.amnezia.vpn.AmneziaVpnService$launchProtocolStateHandler$1$1.emit(AmneziaVpnService.kt:349)
 at org.amnezia.vpn.AmneziaVpnService$launchProtocolStateHandler$1$1$emit$1.invokeSuspend(Unknown Source:15)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:266)
 at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:99)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7940)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ExecInit.main(ExecInit.java:49)
 at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
 at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
 Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@fc233f5, Dispatchers.Main.immediate]
Caused by: android.os.RemoteException: Remote stack trace:
 at com.android.server.ConnectivityService.enforceChangePermission(ConnectivityService.java:2864)
 at com.android.server.ConnectivityService.enforceNetworkRequestPermissions(ConnectivityService.java:6730)
 at com.android.server.ConnectivityService.requestNetwork(ConnectivityService.java:6630)
 at android.net.IConnectivityManager$Stub.onTransact(IConnectivityManager.java:1131)
 at android.os.Binder.execTransactInternal(Binder.java:1309)
```

**Desktop (please complete the following information):**
 - OS: GrapheneOS / Android
 - 13
 
**Smartphone (please complete the following information):**
 - Device: Pixel4a
 - OS: GrapheneOS / Android13
 - Version: latest

**Server (please complete the following information):**
 - OS: ubuntu

**Additional context**
I understand GrapheneOS is very specific, but VPN was established, I saw my VPS IP address for seconds. May be need to allow connection in case of this error. All possible grants provided for application.

**Comment by vlkam** [comment]
I had such problem when I installed old version of Amnezia AmneziaVPN_4.8.2.3_android7_x86_64.apk instead of AmneziaVPN_4.8.2.3_android8+_x86_64.apk
